### ISSUE TITLE
new convertFiles function

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/brukerconverter#31]
Currently we allow to load a zip of a directory but if we are on the web we will have an array of files and it is a waste of time to zip / unzip the files.

We will need a way to directly accept an array of File: https://developer.mozilla.org/en-US/docs/Web/API/File

Or even maybe a FileList: https://developer.mozilla.org/en-US/docs/Web/API/FileList

This is to be tested.

Internally I guess that even if we are using node to convertFolder with a path it could be first converted to a FileList and then forwarded to a new method called `convertFileList`.

We would need to find a shim for FileList in node

`File` is node seems to be implemented in https://www.npmjs.com/package/file-api but there could be alternatives.

**Comment by lpatiny** [comment]
A basic html page showing the API. You can simply drag and drop a folder on the button

```
<p>https://flaviocopes.com/filelist/</p>

<p>
  <input id="fileItem" type="file" webkitdirectory directory multiple />

  <script>
    const input = document.getElementById("fileItem");

    input.addEventListener("change", async (e) => {
      const fileList = input.files;
      const theFile = fileList[0];

      // could also be a stream or a slice !
      const text = await theFile.text();
      const arrayBuffer = await theFile.arrayBuffer();

      console.log(arrayBuffer);
    });
  </script>
</p>
```

**Comment by lpatiny** [comment]
zip entries can easily be converted to File

https://stackoverflow.com/questions/42587203/jszip-extract-file-objects

**Comment by lpatiny** [comment]
@targos I'm trying to find a way to have 'File' in nodejs (as well as FileList but it seems that today we can just consider it is an array of `File`).

The converters (like Brukerconverter) would then accept an array of `File` in the browser and in nodejs from a directory path we should be able to create an array of `File`.

The only implementation of File that I found in nodejs is https://www.npmjs.com/package/File that is pretty old. Did I miss something or should we start to implement it. And if we should implement it what should be the name of this new package ?

**Comment by targos** [comment]
I don't know, implementing the entire File API seems like a waste of time, especially knowing that it will be implemented in Node.js in the future.
Maybe here, instead of relying on the exact File type, we should just have a compatible interface with the methods that we need and make a small utility that returns this interface.

**Comment by lpatiny** [comment]
File and FileList was implemented in this project to continue testing:

https://github.com/cheminfo/brukerconverter/commit/6b510ea0810b4fe65360b6bb1db422ac5f33a5b8

**Comment by lpatiny** [comment]
Closed by https://github.com/cheminfo/brukerconverter/commit/3af21473733cea4506ffe6f534d3fc162d0e9079
