### ISSUE TITLE
Bruker converter input

### ISSUE THREAD

**Issue by andcastillo** [cheminfo/brukerconverter#4]
The brukerconverter has to accept those 2 zipped files. The bruker data could be in the first level of the folfer(single spectrum) or it could be a set of folders each of them containing a single Bruker experiment.
[1D.zip](https://github.com/cheminfo-js/brukerconverter/files/138022/1D.zip)
[toZip.zip](https://github.com/cheminfo-js/brukerconverter/files/138023/toZip.zip)

**Comment by jobo322** [comment]
Currently, the package uses filelist-utils to about the use of zip files. Could you check if this ticket could be closed?

**Comment by jobo322** [comment]
the file toZip works perfectly, but we need at least the folder of the expno. so the file 1D.zip does not work.
