### ISSUE TITLE
Piping Microscopy Data Through Bruker's "Ripper"

### ISSUE THREAD

**Issue by jmdelahanty** [cheminfo/brukerconverter#58]
Hello!

My name is Jeremy and I'm in Dr. Kay Tye's lab here at the Salk Institute. We currently have a Bruker microscope that we use to collect 2-photon data. One of our awesome lab members, Annie, found your repo as a way to pipe data off the scope through Bruker's "ripper" in real time. It looks really neat! I wanted to post here and see if:

- Does this do conversions in real time as data comes off your system?
- Can we use it for this kind of data/does your stuff run on Prairie View also?

Thanks!

**Comment by lpatiny** [comment]
This project deals with Nuclear Magnetic Resonance Bruker spectra and not images. Maybe this project could help: https://github.com/image-js/bruker-afm. but it is currently not very active.

**Comment by jmdelahanty** [comment]
Thanks for the quick response and link to this library! We'll check it out. Good luck with your work!
