### ISSUE TITLE
when a FID is readed, the Re and Im arrays has twice of number of points

### ISSUE THREAD

**Issue by jobo322** [cheminfo/brukerconverter#61]

**Comment by lpatiny** [comment]
Is this related to AQ_mod ?

**Comment by jobo322** [comment]
not, I guess, it is a misunderstanding of the TD parameter. TD is the number of points of the FID, shuffled RE-IM, so the real FID has TD/2 nbpoints, that is why we obtain this zero-filled FID in nmrium.

**Comment by jobo322** [comment]
@lpatiny we should obtain

![image](https://user-images.githubusercontent.com/12143935/194640741-a75501ef-8c15-407f-bbc6-2687529a6641.png)
 
instead of 
![image](https://user-images.githubusercontent.com/12143935/194641130-72651fe6-4178-4e91-9e66-3480cac2dd7f.png)
